version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: familyscheduler
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend
    networks:
      - app-network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgres://admin:123@db:5432/familyscheduler
      - DEBUG=1
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    networks:
      - app-network
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: